import React, { useState, useCallback } from 'react';
import { ChevronLeft, ChevronRight, RotateCcw, CheckCircle2, XCircle, Trophy, BookOpen, Zap, Target, Shield, BarChart3 } from 'lucide-react';

interface Flashcard {
  q: string;
  a: string;
  cat: string;
}

const ALL_CARDS: Flashcard[] = [
  { q: "What is the first step in the Aiva Salesperson workflow?", a: "Sending the offer to employ to the candidate via email or WhatsApp.", cat: "Onboarding & HR" },
  { q: "Which three documents must a new employee bring to the office on their first day?", a: "Identity document, proof of residential address, and bank account confirmation letter.", cat: "Onboarding & HR" },
  { q: "According to the Aiva workflow, what happens to documents 1 to 6 after they are signed?", a: "They are normally scanned and emailed to the employee's business email address.", cat: "Onboarding & HR" },
  { q: "On which day of the month is the employee's salary typically paid?", a: "The 25th day of each month.", cat: "Onboarding & HR" },
  { q: "What is the compulsory requirement regarding the Company's Retirement Fund and Medical Aid?", a: "The employee must join them unless they provide proof of existing medical aid membership.", cat: "Onboarding & HR" },
  { q: "What is the duration of the standard probationary period for a new employee?", a: "3 months.", cat: "Onboarding & HR" },
  { q: "What are the standard daily working hours for Nashua Paarl & West Coast employees?", a: "08h00 to 16h30.", cat: "Onboarding & HR" },
  { q: "Under what condition is an employee entitled to 1.5 times their hourly wage for overtime?", a: "When they work hours in excess of the daily nine agreed hours (excluding Sundays/Public Holidays).", cat: "Onboarding & HR" },
  { q: "How many days of ordinary annual leave is an employee entitled to after 12 months of service?", a: "15 working days.", cat: "Leave & Benefits" },
  { q: "How many days of an employee's annual leave must be taken in December?", a: "10 days.", cat: "Leave & Benefits" },
  { q: "What is the sick leave entitlement for an employee within a 36-month cycle?", a: "30 working days.", cat: "Leave & Benefits" },
  { q: "What is required if an employee is absent for more than two consecutive working days due to illness?", a: "A certificate signed by a registered medical practitioner.", cat: "Leave & Benefits" },
  { q: "What is the minimum period of employment required to qualify for family responsibility leave?", a: "4 months.", cat: "Leave & Benefits" },
  { q: "How many days of paid parental leave is an employee entitled to upon the birth of their child?", a: "10 consecutive days.", cat: "Leave & Benefits" },
  { q: "How many days notice must be given when applying for annual leave?", a: "At least 30 working days.", cat: "Leave & Benefits" },
  { q: "What is the notice period required for an employee during the first six months of service?", a: "1 week.", cat: "Onboarding & HR" },
  { q: "What is the notice period required for an employee after they have completed twelve months of service?", a: "4 weeks.", cat: "Onboarding & HR" },
  { q: "What is the duration of the 'restraint period' following the termination of employment?", a: "2 years.", cat: "Onboarding & HR" },
  { q: "What is the agreed liquidated damages amount for breaching the restraint of trade clause?", a: "R20,000.", cat: "Onboarding & HR" },
  { q: "What is the compulsory retirement age for employees at the company?", a: "60 years old.", cat: "Onboarding & HR" },
  { q: "When is commission typically paid to sales staff?", a: "30 days in arrears.", cat: "Commission & Sales" },
  { q: "In the context of the commission manual, how is 'Net Margin' defined?", a: "The gross profit of the sale.", cat: "Commission & Sales" },
  { q: "What percentage is deducted as a 'Franchise Fee' across all lines of business products?", a: "15%.", cat: "Commission & Sales" },
  { q: "How long are customer quotations valid according to the Commission Manual?", a: "7 working days.", cat: "Commission & Sales" },
  { q: "What is the fixed commission percentage for a Sales Executive on probation?", a: "20% on Margin generated by the sale.", cat: "Commission & Sales" },
  { q: "What is the 'Gate Opener' GP amount required to qualify for any commission payout?", a: "R50,000.", cat: "Commission & Sales" },
  { q: "What is the monthly GP target for an Office Automation (OA) Sales Executive?", a: "R120,000.", cat: "Commission & Sales" },
  { q: "How many total units across different lines of business must be achieved to avoid an 8% GP deduction?", a: "10 units (comprised of specific minimums per line).", cat: "Commission & Sales" },
  { q: "What is the commission rate for a salesperson who is 100%+ on their YTD target?", a: "30% payable on margin.", cat: "Commission & Sales" },
  { q: "For how many months is the ongoing commission for Wireless deals paid on a 36-month contract?", a: "12 months.", cat: "Commission & Sales" },
  { q: "According to the commission manual, who are the sole arbitrators in a commission dispute?", a: "Nashua's Directors and Financial Manager.", cat: "Commission & Sales" },
  { q: "What is the penalty for backdating a quotation?", a: "Commission reversal and potential disciplinary action.", cat: "Commission & Sales" },
  { q: "In the commission calculation formula, what does 'NGP' represent?", a: "Nett Gross Profit (calculated after all costs and fees).", cat: "Commission & Sales" },
  { q: "What is the maximum Nett Margin percentage allowed on any deal?", a: "100% (including franchise fee).", cat: "Commission & Sales" },
  { q: "How is commission handled if an upgrade rule for a 36-60 month contract is violated?", a: "A penalty of at least 3 months' current rental is deducted from the commission.", cat: "Commission & Sales" },
  { q: "What is the 'Quota Club'?", a: "An incentive scheme involving (mostly) overseas travel for qualifying employees.", cat: "Commission & Sales" },
  { q: "What percentage of the 'Quota Club' trip investment must an employee repay if they leave within 6 months of returning?", a: "60%.", cat: "Commission & Sales" },
  { q: "What is the standard monthly unit target for MFPs to earn a +1% commission bonus?", a: "4 units.", cat: "Commission & Sales" },
  { q: "What is the commission payout for a deal with a turnover value of R50,001 or more generated by a Telecanvasser?", a: "1% of the Turnover Value.", cat: "Commission & Sales" },
  { q: "Who must approve all quotations before they are emailed to customers?", a: "The relevant Sales Manager or Sales Director.", cat: "Commission & Sales" },
  { q: "What is the penalty for failing to use Signiflow for contract signatures?", a: "R5,000 per contract.", cat: "Performance & Discipline" },
  { q: "Identify Step 1 in the process for dealing with poor work performance.", a: "Issuing a first poor work performance notification (written warning).", cat: "Performance & Discipline" },
  { q: "What occurs during Step 2 of the poor work performance process?", a: "Training, guidance, counseling, and a fair opportunity to improve.", cat: "Performance & Discipline" },
  { q: "What notification serves as the 'Final Written Warning' in the performance management process?", a: "The second poor work performance notification.", cat: "Performance & Discipline" },
  { q: "Under what condition is Step 5 (Disciplinary Hearing) initiated regarding performance?", a: "When a Sales Executive underperforms within 12 months of receiving a final written warning.", cat: "Performance & Discipline" },
  { q: "What is the notice period required before a disciplinary hearing?", a: "At least 48 hours.", cat: "Performance & Discipline" },
  { q: "Which system must be updated daily with call logs and sales activity to avoid disciplinary action?", a: "iNForm CRM.", cat: "Performance & Discipline" },
  { q: "Under the Performance Policy, what constitutes 'insubordination' regarding measurement?", a: "Causing hindrance to the availability of CRM diaries, call logs, or sales figures.", cat: "Performance & Discipline" },
  { q: "What is the penalty for failing to achieve at least three of the eight line-of-business targets?", a: "A 8% deduction on Gross Profit (GP).", cat: "Performance & Discipline" },
  { q: "What is the standard payment rate for a lead supplied by another staff member?", a: "R250.", cat: "CRM & Operations" },
  { q: "What is the minimum number of confirmed appointments required per day for OA Sales?", a: "5 appointments.", cat: "CRM & Operations" },
  { q: "What is the daily telephone call target for a Lead Generator / Appointment Setter?", a: "80 calls.", cat: "CRM & Operations" },
  { q: "Between what hours are Sales Executives expected to be out of the office visiting clients?", a: "10h00 and 15h00 daily.", cat: "CRM & Operations" },
  { q: "What is the name of Nashua's chosen Customer Relationship Management (CRM) solution?", a: "iNForm.", cat: "CRM & Operations" },
  { q: "What is the purpose of the 'ProAct' platform?", a: "Remote monitoring and management of networked office automation devices.", cat: "CRM & Operations" },
  { q: "What percentage of the total Machines in Field (MIF) must a franchise have loaded onto ProAct?", a: "70%.", cat: "CRM & Operations" },
  { q: "If no CRM activity is recorded for _____ months on an account, it may be reassigned.", a: "3 months.", cat: "CRM & Operations" },
  { q: "What is the fixed factor used for deals self-financed by Nashua?", a: "1.7.", cat: "CRM & Operations" },
  { q: "What is the required monthly telephone call target for Consumable Sales?", a: "700 calls.", cat: "CRM & Operations" },
  { q: "What happens if a deal is handed over to the legal department within 12 months of a 36-month contract?", a: "A commission reversal occurs on that specific deal.", cat: "CRM & Operations" },
  { q: "What document must be signed by Technical before equipment commission is paid?", a: "Post Installation sign-off via Signiflow.", cat: "CRM & Operations" },
  { q: "What is the primary purpose of the Sales Executive position?", a: "To maintain and grow company market share and market the full range of Nashua products.", cat: "CRM & Operations" },
  { q: "How often are 'Corporate' clients required to be visited by Sales Executives?", a: "Monthly.", cat: "CRM & Operations" },
  { q: "How often are 'Other Existing' clients required to be visited?", a: "Quarterly.", cat: "CRM & Operations" },
  { q: "What is the 'Earnings Threshold' mentioned in the employment contract?", a: "The limit above which certain BCEA protections (like overtime pay) no longer apply.", cat: "Onboarding & HR" },
  { q: "What is the required lead response time once a lead is received via electronic communication?", a: "Contact within one hour.", cat: "CRM & Operations" },
  { q: "What happens to a lead if it is not attended to within 24 hours?", a: "It is passed on to another Sales Executive.", cat: "CRM & Operations" },
  { q: "What is the daily cold call target for OA Sales Executives?", a: "5 calls.", cat: "CRM & Operations" },
  { q: "What is the daily quote target for Consumable Sales?", a: "10 quotes.", cat: "CRM & Operations" },
  { q: "Which act governs the company's right to gain access to an employee's electronic communications?", a: "Regulation of Interception of Communications and Provision of Communication-related Information Act.", cat: "Onboarding & HR" },
  { q: "What is the 'Protection Cover' requirement for capitalized equipment?", a: "It is compulsory at a rate of 4% of cost.", cat: "CRM & Operations" },
];

const CATEGORIES = ['All', 'Onboarding & HR', 'Leave & Benefits', 'Commission & Sales', 'Performance & Discipline', 'CRM & Operations'];

const CAT_CONFIG: Record<string, { icon: React.FC<any>; color: string; bg: string }> = {
  'All':                    { icon: BookOpen,   color: 'text-[#0d9488]',  bg: 'bg-[#0d9488]/10' },
  'Onboarding & HR':        { icon: Target,     color: 'text-blue-400',   bg: 'bg-blue-400/10' },
  'Leave & Benefits':       { icon: Shield,     color: 'text-emerald-400',bg: 'bg-emerald-400/10' },
  'Commission & Sales':     { icon: BarChart3,  color: 'text-amber-400',  bg: 'bg-amber-400/10' },
  'Performance & Discipline':{ icon: Zap,       color: 'text-red-400',    bg: 'bg-red-400/10' },
  'CRM & Operations':       { icon: Target,     color: 'text-purple-400', bg: 'bg-purple-400/10' },
};

export const FlashcardTrainer: React.FC = () => {
  const [selectedCat, setSelectedCat] = useState('All');
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [known, setKnown] = useState<Set<number>>(new Set());
  const [reviewing, setReviewing] = useState<Set<number>>(new Set());
  const [sessionComplete, setSessionComplete] = useState(false);
  const [animDir, setAnimDir] = useState<'left' | 'right' | null>(null);

  const filteredCards = selectedCat === 'All'
    ? ALL_CARDS
    : ALL_CARDS.filter(c => c.cat === selectedCat);

  const card = filteredCards[currentIndex];
  const progress = ((currentIndex) / filteredCards.length) * 100;

  const navigate = useCallback((dir: 'next' | 'prev') => {
    setAnimDir(dir === 'next' ? 'left' : 'right');
    setIsFlipped(false);
    setTimeout(() => {
      if (dir === 'next') {
        if (currentIndex >= filteredCards.length - 1) {
          setSessionComplete(true);
        } else {
          setCurrentIndex(i => i + 1);
        }
      } else {
        setCurrentIndex(i => Math.max(0, i - 1));
      }
      setAnimDir(null);
    }, 200);
  }, [currentIndex, filteredCards.length]);

  const markKnown = () => {
    setKnown(s => new Set([...s, currentIndex]));
    navigate('next');
  };

  const markReview = () => {
    setReviewing(s => new Set([...s, currentIndex]));
    navigate('next');
  };

  const reset = () => {
    setCurrentIndex(0);
    setIsFlipped(false);
    setKnown(new Set());
    setReviewing(new Set());
    setSessionComplete(false);
  };

  const changeCategory = (cat: string) => {
    setSelectedCat(cat);
    setCurrentIndex(0);
    setIsFlipped(false);
    setKnown(new Set());
    setReviewing(new Set());
    setSessionComplete(false);
  };

  const catCfg = CAT_CONFIG[card?.cat] || CAT_CONFIG['All'];

  if (sessionComplete) {
    const score = known.size;
    const total = filteredCards.length;
    const pct = Math.round((score / total) * 100);
    return (
      <div className="flex flex-col items-center justify-center min-h-[500px] animate-fadeIn">
        <div className="bg-white dark:bg-[#1a1f2e] rounded-[3rem] p-12 text-center max-w-lg w-full border border-slate-100 dark:border-white/10 shadow-2xl">
          <div className="w-24 h-24 rounded-full bg-[#0d9488]/10 flex items-center justify-center mx-auto mb-6">
            <Trophy className="w-12 h-12 text-[#0d9488]" />
          </div>
          <h2 className="text-3xl font-black text-slate-900 dark:text-white uppercase italic tracking-tighter mb-2">Session Complete!</h2>
          <p className="text-slate-500 text-sm font-bold uppercase tracking-widest mb-8">{selectedCat}</p>
          <div className="text-7xl font-black text-[#0d9488] mb-2">{pct}%</div>
          <p className="text-slate-400 text-xs font-black uppercase tracking-widest mb-8">{score} of {total} cards known</p>
          <div className="grid grid-cols-2 gap-4 mb-8">
            <div className="bg-emerald-50 dark:bg-emerald-500/10 rounded-2xl p-4">
              <div className="text-2xl font-black text-emerald-500">{known.size}</div>
              <div className="text-[9px] font-black text-slate-400 uppercase tracking-widest mt-1">Got It</div>
            </div>
            <div className="bg-amber-50 dark:bg-amber-500/10 rounded-2xl p-4">
              <div className="text-2xl font-black text-amber-500">{reviewing.size}</div>
              <div className="text-[9px] font-black text-slate-400 uppercase tracking-widest mt-1">Review Again</div>
            </div>
          </div>
          <button
            onClick={reset}
            className="w-full py-4 bg-[#0d9488] hover:bg-[#0a7c72] text-white font-black rounded-2xl uppercase tracking-widest text-xs transition-all flex items-center justify-center gap-2 shadow-lg"
          >
            <RotateCcw className="w-4 h-4" /> Restart Session
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fadeIn pb-20">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-black text-slate-900 dark:text-white uppercase italic tracking-tighter leading-none">Policy Flashcards</h2>
          <p className="text-slate-500 dark:text-slate-400 text-[10px] uppercase font-black tracking-widest mt-1">Nashua Paarl Knowledge Registry · {ALL_CARDS.length} Cards</p>
        </div>
        <button onClick={reset} className="flex items-center gap-2 px-4 py-2 text-[9px] font-black uppercase tracking-widest text-slate-400 hover:text-[#0d9488] transition-colors">
          <RotateCcw className="w-3.5 h-3.5" /> Reset
        </button>
      </div>

      {/* Category Pills */}
      <div className="flex flex-wrap gap-2">
        {CATEGORIES.map(cat => {
          const cfg = CAT_CONFIG[cat];
          const Icon = cfg.icon;
          const count = cat === 'All' ? ALL_CARDS.length : ALL_CARDS.filter(c => c.cat === cat).length;
          return (
            <button
              key={cat}
              onClick={() => changeCategory(cat)}
              className={`flex items-center gap-2 px-4 py-2 rounded-xl text-[9px] font-black uppercase tracking-wider transition-all border ${
                selectedCat === cat
                  ? `${cfg.bg} ${cfg.color} border-current shadow-sm`
                  : 'bg-white dark:bg-white/5 text-slate-400 border-slate-100 dark:border-white/5 hover:border-slate-200'
              }`}
            >
              <Icon className="w-3 h-3" />
              {cat === 'All' ? 'All Cards' : cat.split(' & ')[0]}
              <span className="opacity-60">{count}</span>
            </button>
          );
        })}
      </div>

      {/* Progress Bar */}
      <div className="space-y-2">
        <div className="flex justify-between text-[9px] font-black uppercase tracking-widest text-slate-400">
          <span>Card {currentIndex + 1} of {filteredCards.length}</span>
          <span className="flex gap-4">
            <span className="text-emerald-500">{known.size} Known</span>
            <span className="text-amber-500">{reviewing.size} Review</span>
          </span>
        </div>
        <div className="h-1.5 bg-slate-100 dark:bg-white/5 rounded-full overflow-hidden">
          <div
            className="h-full bg-[#0d9488] rounded-full transition-all duration-500"
            style={{ width: `${progress}%` }}
          />
        </div>
      </div>

      {/* Flashcard */}
      <div className="flex justify-center">
        <div
          className="relative w-full max-w-2xl cursor-pointer"
          style={{ perspective: '1200px', height: '320px' }}
          onClick={() => setIsFlipped(f => !f)}
        >
          <div
            className="relative w-full h-full transition-all duration-500"
            style={{
              transformStyle: 'preserve-3d',
              transform: isFlipped ? 'rotateY(180deg)' : 'rotateY(0deg)',
              opacity: animDir ? 0 : 1,
              transition: animDir ? 'opacity 0.2s' : 'transform 0.5s cubic-bezier(0.4,0,0.2,1), opacity 0.2s',
            }}
          >
            {/* Front */}
            <div
              className="absolute inset-0 bg-white dark:bg-[#1a1f2e] rounded-[2.5rem] border border-slate-100 dark:border-white/10 shadow-xl p-10 flex flex-col justify-between"
              style={{ backfaceVisibility: 'hidden' }}
            >
              <div className="flex items-center justify-between">
                <span className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-[8px] font-black uppercase tracking-wider ${catCfg.bg} ${catCfg.color}`}>
                  <catCfg.icon className="w-3 h-3" />
                  {card?.cat}
                </span>
                <span className="text-[9px] font-black text-slate-300 dark:text-slate-600 uppercase tracking-widest">Tap to Reveal</span>
              </div>
              <div className="flex-1 flex items-center justify-center px-4">
                <p className="text-xl font-bold text-slate-800 dark:text-white text-center leading-relaxed">{card?.q}</p>
              </div>
              <div className="flex justify-center">
                <div className="flex gap-1">
                  {[0,1,2].map(i => (
                    <div key={i} className={`w-1.5 h-1.5 rounded-full transition-all ${i === 1 ? 'bg-[#0d9488]' : 'bg-slate-200 dark:bg-white/10'}`} />
                  ))}
                </div>
              </div>
            </div>

            {/* Back */}
            <div
              className="absolute inset-0 bg-[#0d9488] rounded-[2.5rem] shadow-xl p-10 flex flex-col justify-between"
              style={{ backfaceVisibility: 'hidden', transform: 'rotateY(180deg)' }}
            >
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-[8px] font-black uppercase tracking-wider bg-white/20 text-white">
                  Answer
                </span>
                <span className="text-[9px] font-black text-white/50 uppercase tracking-widest">Tap to Flip Back</span>
              </div>
              <div className="flex-1 flex items-center justify-center px-4">
                <p className="text-2xl font-black text-white text-center leading-relaxed">{card?.a}</p>
              </div>
              <div className="flex justify-center">
                <div className="flex gap-1">
                  {[0,1,2].map(i => (
                    <div key={i} className={`w-1.5 h-1.5 rounded-full transition-all ${i === 1 ? 'bg-white' : 'bg-white/30'}`} />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Controls */}
      <div className="flex items-center justify-center gap-4 flex-wrap">
        <button
          onClick={() => navigate('prev')}
          disabled={currentIndex === 0}
          className="p-3 rounded-xl bg-white dark:bg-white/5 border border-slate-100 dark:border-white/10 text-slate-400 hover:text-slate-700 disabled:opacity-30 transition-all shadow-sm"
        >
          <ChevronLeft className="w-5 h-5" />
        </button>

        {isFlipped ? (
          <>
            <button
              onClick={markReview}
              className="flex items-center gap-2 px-6 py-3 bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/20 text-amber-600 dark:text-amber-400 font-black rounded-xl uppercase tracking-widest text-[10px] hover:bg-amber-100 transition-all"
            >
              <XCircle className="w-4 h-4" /> Review Again
            </button>
            <button
              onClick={markKnown}
              className="flex items-center gap-2 px-6 py-3 bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/20 text-emerald-600 dark:text-emerald-400 font-black rounded-xl uppercase tracking-widest text-[10px] hover:bg-emerald-100 transition-all"
            >
              <CheckCircle2 className="w-4 h-4" /> Got It
            </button>
          </>
        ) : (
          <button
            onClick={() => setIsFlipped(true)}
            className="flex items-center gap-2 px-8 py-3 bg-[#0d9488] text-white font-black rounded-xl uppercase tracking-widest text-[10px] hover:bg-[#0a7c72] transition-all shadow-md"
          >
            Reveal Answer
          </button>
        )}

        <button
          onClick={() => navigate('next')}
          className="p-3 rounded-xl bg-white dark:bg-white/5 border border-slate-100 dark:border-white/10 text-slate-400 hover:text-slate-700 transition-all shadow-sm"
        >
          <ChevronRight className="w-5 h-5" />
        </button>
      </div>

      {/* Mini stats row */}
      <div className="grid grid-cols-5 gap-3 max-w-2xl mx-auto">
        {CATEGORIES.slice(1).map(cat => {
          const cfg = CAT_CONFIG[cat];
          const Icon = cfg.icon;
          const count = ALL_CARDS.filter(c => c.cat === cat).length;
          return (
            <button key={cat} onClick={() => changeCategory(cat)}
              className={`flex flex-col items-center p-3 rounded-2xl border transition-all ${selectedCat === cat ? `${cfg.bg} border-current ${cfg.color}` : 'bg-white dark:bg-white/5 border-slate-100 dark:border-white/5 text-slate-400 hover:border-slate-200'}`}>
              <Icon className="w-4 h-4 mb-1" />
              <span className="text-lg font-black">{count}</span>
              <span className="text-[7px] font-black uppercase tracking-widest leading-tight text-center opacity-70">
                {cat.split(' & ')[0]}
              </span>
            </button>
          );
        })}
      </div>
    </div>
  );
};
